### Listando todos elementos
GET http://localhost:3000/eventos

### Criar evento
POST http://localhost:3000/eventos
Content-Type: application/json

{
    "titulo": "Evento Teste",
    "descricao": "Descrição do evento",
    "vagas": 50,
    "modalidade": "presencial",
    "cargaHoraria": 8
}

### Buscando evento por ID
GET http://localhost:3000/eventos/2

####
GET http://localhost:3000/api/eventos

####
GET http://localhost:3000/api/eventos/1/cancelar
####
GET http://localhost:3000/api/eventos/1/inscricao

### Atualizar evento
PUT http://localhost:3000/eventos/1
Content-Type: application/json

{
  "titulo": "Workshop Atualizado",
  "vagas": 50
}

### Remover evento
DELETE http://localhost:3000/eventos/1

### Listar ativos
GET http://localhost:3000/eventos/ativos